Iteration 10 Seperating HAVE_SSE42 and HAVE_PCLMUL
Summary:
We do test compiling in build_detect_platform and set HAVE_SSE42 if compiler
supports both SSE42 and PCLMUL intrinsics. For safty reasons we are seperating
them to be HAVE_SSE42 and HAVE_PCLMUL

Test Plan:
make clean && make -j64 db_bench
make clean && NO_THREEWAY_CRC32C=1 make -j64 db_bench

Modify build_tools/build_detect_platform to remove 1) HAVE_SSE42 2) HAVE_PCLMUL
then build and run again

Reviewers:
andrewkr, jodent, svemuri

Subscribers:
yingsu, andrewkr, jodent, svemuri

Tasks:
T20949442

Tags:

Blame Revision:

diff --git a/build_tools/build_detect_platform b/build_tools/build_detect_platform
--- a/build_tools/build_detect_platform
+++ b/build_tools/build_detect_platform
@@ -463,9 +463,21 @@ fi
 $CXX $PLATFORM_CXXFLAGS $COMMON_FLAGS -x c++ - -o /dev/null 2>/dev/null <<EOF
   #include <cstdint>
   #include <nmmintrin.h>
-  #include <wmmintrin.h>
   int main() {
     volatile uint32_t x = _mm_crc32_u32(0, 0);
+  }
+EOF
+if [ "$?" = 0 ]; then
+  COMMON_FLAGS="$COMMON_FLAGS -DHAVE_SSE42"
+elif test "$USE_SSE"; then
+  echo "warning: USE_SSE specified but compiler could not use SSE intrinsics, disabling"
+  exit 1
+fi
+
+$CXX $PLATFORM_CXXFLAGS $COMMON_FLAGS -x c++ - -o /dev/null 2>/dev/null <<EOF
+  #include <cstdint>
+  #include <wmmintrin.h>
+  int main() {
     const auto a = _mm_set_epi64x(0, 0);
     const auto b = _mm_set_epi64x(0, 0);
     const auto c = _mm_clmulepi64_si128(a, b, 0x00);
@@ -473,9 +485,9 @@ $CXX $PLATFORM_CXXFLAGS $COMMON_FLAGS -x c++ - -o /dev/null 2>/dev/null <<EOF
   }
 EOF
 if [ "$?" = 0 ]; then
-  COMMON_FLAGS="$COMMON_FLAGS -DHAVE_SSE42"
+  COMMON_FLAGS="$COMMON_FLAGS -DHAVE_PCLMUL"
 elif test "$USE_SSE"; then
-  echo "warning: USE_SSE specified but compiler could not use SSE intrinsics, disabling"
+  echo "warning: USE_SSE specified but compiler could not use PCLMUL intrinsics, disabling"
   exit 1
 fi
 
