Attempt fixes

diff --git a/build_tools/build_detect_platform b/build_tools/build_detect_platform
--- a/build_tools/build_detect_platform
+++ b/build_tools/build_detect_platform
@@ -45,39 +45,6 @@ if test -z "$OUTPUT"; then
   exit 1
 fi
 
-# we depend on C++20, but should be compatible with newer standards
-if [ "$ROCKSDB_CXX_STANDARD" ]; then
-  PLATFORM_CXXFLAGS="-std=$ROCKSDB_CXX_STANDARD"
-else
-  PLATFORM_CXXFLAGS="-std=c++20"
-fi
-
-# we currently depend on POSIX platform
-COMMON_FLAGS="-DROCKSDB_PLATFORM_POSIX -DROCKSDB_LIB_IO_POSIX"
-
-# Default to fbcode gcc on Meta internal machines
-IS_META_HOST="$(hostname | grep -E '(facebook|meta).com|fbinfra.net')"
-if [ -z "$ROCKSDB_NO_FBCODE" -a "$IS_META_HOST" ]; then
-  if [ -d /mnt/gvfs/third-party ]; then
-    echo "NOTE: Using fbcode build" >&2
-    FBCODE_BUILD="true"
-    # If we're compiling with TSAN or shared lib, we need pic build
-    PIC_BUILD=$COMPILE_WITH_TSAN
-    if [ "$LIB_MODE" == "shared" ]; then
-      PIC_BUILD=1
-    fi
-    source "$PWD/build_tools/fbcode_config_platform010.sh"
-  else
-    echo "************************************************************************" >&2
-    echo "WARNING: -d /mnt/gvfs/third-party failed; no fbcode build" >&2
-    echo "************************************************************************" >&2
-  fi
-fi
-
-# Delete existing output, if it exists
-rm -f "$OUTPUT"
-touch "$OUTPUT"
-
 if test -z "$CC"; then
     if [ "$USE_CLANG" -a -x "$(command -v clang)" ]; then
         CC=clang
@@ -113,6 +80,46 @@ if test -z "$AR"; then
         AR=ar
     fi
 fi
+
+# we depend on C++20, but should be compatible with newer standards
+if [ "$ROCKSDB_CXX_STANDARD" ]; then
+  PLATFORM_CXXFLAGS="-std=$ROCKSDB_CXX_STANDARD"
+else
+  PLATFORM_CXXFLAGS="-std=c++20"
+  $CXX $PLATFORM_CXXFLAGS -x c++ - -o test.o 2>/dev/null  <<EOF
+          int main() {}
+EOF
+  if [ "$?" != 0 ]; then
+    # old name (e.g. GCC 10)
+    PLATFORM_CXXFLAGS="-std=c++2a"
+  fi
+fi
+
+# we currently depend on POSIX platform
+COMMON_FLAGS="-DROCKSDB_PLATFORM_POSIX -DROCKSDB_LIB_IO_POSIX"
+
+# Default to fbcode gcc on Meta internal machines
+IS_META_HOST="$(hostname | grep -E '(facebook|meta).com|fbinfra.net')"
+if [ -z "$ROCKSDB_NO_FBCODE" -a "$IS_META_HOST" ]; then
+  if [ -d /mnt/gvfs/third-party ]; then
+    echo "NOTE: Using fbcode build" >&2
+    FBCODE_BUILD="true"
+    # If we're compiling with TSAN or shared lib, we need pic build
+    PIC_BUILD=$COMPILE_WITH_TSAN
+    if [ "$LIB_MODE" == "shared" ]; then
+      PIC_BUILD=1
+    fi
+    source "$PWD/build_tools/fbcode_config_platform010.sh"
+  else
+    echo "************************************************************************" >&2
+    echo "WARNING: -d /mnt/gvfs/third-party failed; no fbcode build" >&2
+    echo "************************************************************************" >&2
+  fi
+fi
+
+# Delete existing output, if it exists
+rm -f "$OUTPUT"
+touch "$OUTPUT"
 
 # Detect OS
 if test -z "$TARGET_OS"; then
